### ISSUE TITLE
Get all alert levels

### ISSUE THREAD

**Issue by bpeng** [GeoNet/geonet-rest#87]
It would be ideal to provide restful service to get all alert levels in json format, otherwise the alert levels need to be hard coded elsewhere in different apps.

**Comment by gclitheroe** [comment]
Hi Baishan,

Sounds like a good idea.  if you are needing these level in haz-admin then please use the public vars from msg -  I want haz-admin to as independent of the DB and web services as possible.

If you're needing them for phone apps etc then a service from here make sense.  What do you think about a route like

```
/dictionary/volcano/alertlevels
```

to make it clear it's separate from the data?

-G
