### ISSUE TITLE
Volcano urls

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/geonet-rest#89]
Hi @junghao 

I've currently got volcano urls like

```
/volcano/alertlevel
/volcano/alertbulletin
```

and  I feel like it would be more consistent with the style of the rest of the api to have

```
/volcano/alert/level
/volcano/alert/bulletin
```

If you agree please could you make the change?

**Comment by junghao** [comment]
Do we need something like /volcano/info?id=whiteisland
When the user tap volcano in the list we'll have to bring them to the volcano's description. (Or display alert level change history / VAB ?) 

(This list is based on alertlevel api which contains geometry and volcano id only)
![ios simulator screen shot 24 06 2015 3 36 00 pm](https://cloud.githubusercontent.com/assets/8474881/8322270/caeb977a-1a86-11e5-9901-07769043a477.png)

**Comment by junghao** [comment]
Same issue in this screen.

![ios simulator screen shot 24 06 2015 3 40 20 pm](https://cloud.githubusercontent.com/assets/8474881/8322326/66f09e5e-1a87-11e5-9a9e-b1b89b490ff2.png)

**Comment by gclitheroe** [comment]
I think we will need something like this but I don't have a good idea where the content will come from yet.

**Comment by gclitheroe** [comment]
This ticket is about the services to build the map first...

**Comment by junghao** [comment]
OK I create another ticket.
