### ISSUE TITLE
"news" api need "label" filter in order to display news for volcano

### ISSUE THREAD

**Issue by junghao** [GeoNet/geonet-rest#92]
1. news api doesn't accept parameter
2. Currently the "newsURL" var in news.go has a "labelString=" (set to empty) , it should able to take parameter.

**Comment by gclitheroe** [comment]
It looks like it's gone from the latest version of the feed URL.  I just see this now

http://info.geonet.org.nz/createrssfeed.action?types=blogpost&spaces=conf_all&title=GeoNet+News+RSS+Feed&labelString%3D&excludedSpaceKeys%3D&sort=created&maxResults=10&timeSpan=500&showContent=true&publicFeed=true&confirm=Create+RSS+Feed

Which I got from here http://info.geonet.org.nz/display/home/Information+at+your+fingertips

**Comment by junghao** [comment]
I think the url works ( with labelString=volcano or =vab ). So all we need to do is let news.go accept label parameter.

**Comment by gclitheroe** [comment]
So what is it you need?  Don't forget the VAB code is already done just not deployed yet?  Are you thinking we replace that with a labelString query param?

**Comment by junghao** [comment]
Will there be news labeled by "volcano" only? Not a vab.

**Comment by kfenaugh** [comment]
Yes, there will be news with just 'volcano'.
